jobs:
  run-linting:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn run lint
orbs:
  node: circleci/node@4.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - run-linting
